### ISSUE TITLE
scale problem

### ISSUE THREAD

**Issue by 0ldi** [laytya/MinimapButtonBag-vanilla#1]
It's not a big deal, but not nice
http://imagehost.spark-media.ru/i4/0B87B5EA-531B-8ED6-10AC-D6ACF1173664.png
Here is the MBB at the interface scale 0.64 and the scale of the minimap 0.85 (yes I really do not need a big minimap, it is convenient for me). In fact WIM button bagged , but it is normal size of the buttons was before to use MBB and it would be nice that all buttons scaling. Because at this point the diameter of all the buttons is 1\3 of the width of the mini-map, and as you see this is not very convenient.

**Comment by 0ldi** [comment]
And i am not sure, but sometimes when i load into the game i have this crit error with log:
Is that MBB bug?

> # 
> 
> World of WarCraft (build 5875)

Exe:      C:\World of Warcraft Classic2\WoW.exe
Time:     Oct 26, 2016  1:52:59.008 PM
User:     Admin

## Computer: MACHINE

This application has encountered a critical error:

ERROR #132 (0x85100084) Fatal Exception
Program:    C:\World of Warcraft Classic2\WoW.exe
Exception:  0xC0000005 (ACCESS_VIOLATION) at 0023:007A2452

The instruction at "0x007A2452" referenced memory at "0x10EF3FE8".
The memory could not be "read".

## WoWBuild: 5875

---

```
x86 Registers
```

---

EAX=26280208  EBX=10EF3FE4  ECX=00000000  EDX=25B94A35  ESI=0E222188
EDI=20AD5A28  EBP=0019FB28  ESP=0019FB18  EIP=007A2452  FLG=00210202
CS =0023      DS =002B      ES =002B      SS =002B      FS =0053      GS =002B

---

```
Stack Trace (Manual)
```

---

Address  Frame    Logical addr  Module

007A2452 0019FB28 0001:003A1452 C:\World of Warcraft Classic2\WoW.exe
006F61AA 0019FB40 0001:002F51AA C:\World of Warcraft Classic2\WoW.exe
006F9231 0019FB88 0001:002F8231 C:\World of Warcraft Classic2\WoW.exe
006F65EF 0019FB98 0001:002F55EF C:\World of Warcraft Classic2\WoW.exe
006F425B 0019FC00 0001:002F325B C:\World of Warcraft Classic2\WoW.exe
006F699B 0019FC28 0001:002F599B C:\World of Warcraft Classic2\WoW.exe
006F423C 0019FC4C 0001:002F323C C:\World of Warcraft Classic2\WoW.exe
0070519E 0019FCDC 0001:0030419E C:\World of Warcraft Classic2\WoW.exe
00702747 0019FCF8 0001:00301747 C:\World of Warcraft Classic2\WoW.exe
00702708 0019FD10 0001:00301708 C:\World of Warcraft Classic2\WoW.exe
0076B2E8 0019FD2C 0001:0036A2E8 C:\World of Warcraft Classic2\WoW.exe
00765713 0019FD5C 0001:00364713 C:\World of Warcraft Classic2\WoW.exe
00764345 0019FD6C 0001:00363345 C:\World of Warcraft Classic2\WoW.exe
0044264E 0019FE34 0001:0004164E C:\World of Warcraft Classic2\WoW.exe
004246B0 0019FE68 0001:000236B0 C:\World of Warcraft Classic2\WoW.exe
0042106F 0019FED8 0001:0002006F C:\World of Warcraft Classic2\WoW.exe
00420BF1 0019FEF0 0001:0001FBF1 C:\World of Warcraft Classic2\WoW.exe
0040411E 0019FF80 0001:0000311E C:\World of Warcraft Classic2\WoW.exe
76EB62C4 0019FF94 0001:000062C4 C:\Windows\System32\KERNEL32.DLL
77530609 0019FFDC 0001:0005F609 C:\Windows\SYSTEM32\ntdll.dll
775305D4 0019FFEC 0001:0005F5D4 C:\Windows\SYSTEM32\ntdll.dll

---

```
Stack Trace (Using DBGHELP.DLL)
```

---

007A2452 WoW.exe      <unknown symbol>+0 (0x0E222188,0x04010019,0xFFFFFFFF,0x000001D0)

---

```
Loaded Modules
```

---

0x00400000 - 0x00D06000  C:\World of Warcraft Classic2\WoW.exe
0x02B50000 - 0x02BE6000  C:\World of Warcraft Classic2\fmod.dll
0x05440000 - 0x0546D000  C:\Windows\System32\ExSrv.dll
0x10000000 - 0x10069000  C:\World of Warcraft Classic2\DivxDecoder.dll
0x3E000000 - 0x3E118000  C:\World of Warcraft Classic2\dbghelp.dll
0x5D0E0000 - 0x5D159000  C:\Windows\AppPatch\AcSpecfc.DLL
0x5D4F0000 - 0x5D579000  C:\Windows\SYSTEM32\dsound.dll
0x5EBB0000 - 0x5EBB8000  C:\Windows\SYSTEM32\WSOCK32.dll
0x62640000 - 0x62648000  C:\Windows\SYSTEM32\midimap.dll
0x62F70000 - 0x62F7A000  C:\Windows\SYSTEM32\msacm32.drv
0x62FE0000 - 0x63019000  C:\Windows\SYSTEM32\wdmaud.drv
0x633E0000 - 0x6376B000  C:\Windows\SYSTEM32\msi.dll
0x64280000 - 0x64305000  C:\Windows\SYSTEM32\mscms.dll
0x66990000 - 0x67760000  C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_78c173b1404a4b4e\nvd3dum.dll
0x6C940000 - 0x6C947000  C:\Windows\SYSTEM32\ksuser.dll
0x6E8F0000 - 0x6E9B7000  C:\Program Files (x86)\NVIDIA Corporation\3D Vision\nvSCPAPI.dll
0x6EF80000 - 0x6F0E2000  C:\Windows\system32\nvspcap.dll
0x6FC80000 - 0x6FD01000  C:\Windows\SYSTEM32\sxs.dll
0x6FD10000 - 0x6FD17000  C:\Windows\SYSTEM32\DCIMAN32.dll
0x6FE90000 - 0x6FF7D000  C:\Windows\SYSTEM32\DDRAW.dll
0x6FF80000 - 0x6FFA5000  C:\Windows\SYSTEM32\GLU32.dll
0x6FFB0000 - 0x70090000  C:\Windows\SYSTEM32\OPENGL32.dll
0x702B0000 - 0x702B9000  C:\Windows\SYSTEM32\AVRT.dll
0x70380000 - 0x704DF000  C:\Windows\SYSTEM32\d3d9.dll
0x704F0000 - 0x70719000  C:\Windows\SYSTEM32\iertutil.dll
0x70720000 - 0x70736000  C:\Windows\SYSTEM32\MPR.dll
0x70740000 - 0x708D3000  C:\Windows\SYSTEM32\urlmon.dll
0x708E0000 - 0x708F8000  C:\Windows\SYSTEM32\MSACM32.dll
0x70B90000 - 0x70C22000  C:\Windows\system32\apphelp.dll
0x711B0000 - 0x712FF000  C:\Windows\System32\PROPSYS.dll
0x71300000 - 0x713CF000  C:\Windows\SYSTEM32\wintypes.dll
0x713D0000 - 0x71428000  C:\Windows\System32\MMDevApi.dll
0x71430000 - 0x714AB000  C:\Windows\SYSTEM32\AUDIOSES.DLL
0x714B0000 - 0x714D2000  C:\Windows\System32\DEVOBJ.dll
0x71750000 - 0x71773000  C:\Windows\SYSTEM32\WINMMBASE.dll
0x71780000 - 0x717A4000  C:\Windows\SYSTEM32\WINMM.dll
0x71CE0000 - 0x71F0E000  C:\Windows\SYSTEM32\WININET.dll
0x72B90000 - 0x72C24000  C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.14393.0_none_88fef4c26039fb25\COMCTL32.dll
0x72C30000 - 0x72C9A000  C:\Windows\SYSTEM32\WINSPOOL.DRV
0x72DA0000 - 0x72DA8000  C:\Windows\SYSTEM32\WINNSI.DLL
0x72E30000 - 0x72E40000  C:\Windows\SYSTEM32\ondemandconnroutehelper.dll
0x72E40000 - 0x72EBC000  C:\Windows\SYSTEM32\DNSAPI.dll
0x72EC0000 - 0x73245000  C:\Windows\system32\nvapi.dll
0x73290000 - 0x73298000  C:\Windows\System32\rasadhlp.dll
0x732A0000 - 0x732E9000  C:\Windows\System32\fwpuclnt.dll
0x732F0000 - 0x732FC000  C:\Windows\System32\winrnr.dll
0x73300000 - 0x73314000  C:\Windows\system32\NLAapi.dll
0x73320000 - 0x73336000  C:\Windows\system32\pnrpnsp.dll
0x73340000 - 0x73352000  C:\Windows\system32\napinsp.dll
0x73360000 - 0x733E4000  C:\Windows\SYSTEM32\dxgi.dll
0x733F0000 - 0x7343E000  C:\Windows\SYSTEM32\mswsock.dll
0x735B0000 - 0x735CB000  C:\Windows\SYSTEM32\bcrypt.dll
0x73620000 - 0x7363F000  C:\Windows\SYSTEM32\dwmapi.dll
0x73680000 - 0x736A8000  C:\Windows\SYSTEM32\ntmarta.dll
0x737A0000 - 0x7383F000  C:\Windows\SYSTEM32\WINHTTP.dll
0x73840000 - 0x7386F000  C:\Windows\SYSTEM32\IPHLPAPI.DLL
0x73AA0000 - 0x73B15000  C:\Windows\system32\uxtheme.dll
0x73D20000 - 0x73D3A000  C:\Windows\SYSTEM32\USERENV.dll
0x73F70000 - 0x73F78000  C:\Windows\SYSTEM32\VERSION.dll
0x73F80000 - 0x73F8A000  C:\Windows\System32\CRYPTBASE.dll
0x73F90000 - 0x73FAE000  C:\Windows\System32\SspiCli.dll
0x73FB0000 - 0x73FF5000  C:\Windows\System32\powrprof.dll
0x74170000 - 0x742CB000  C:\Windows\System32\gdi32full.dll
0x742D0000 - 0x744E1000  C:\Windows\System32\combase.dll
0x744F0000 - 0x74567000  C:\Windows\System32\ADVAPI32.dll
0x746F0000 - 0x74736000  C:\Windows\System32\SHLWAPI.dll
0x74740000 - 0x7482A000  C:\Windows\System32\ole32.dll
0x74830000 - 0x748EE000  C:\Windows\System32\msvcrt.dll
0x748F0000 - 0x7491B000  C:\Windows\System32\GDI32.dll
0x74920000 - 0x7492F000  C:\Windows\System32\profapi.dll
0x74930000 - 0x75D07000  C:\Windows\System32\SHELL32.dll
0x75D10000 - 0x7611B000  C:\Windows\System32\SETUPAPI.dll
0x76120000 - 0x7612D000  C:\Windows\System32\kernel.appcore.dll
0x76130000 - 0x76136000  C:\Windows\System32\PSAPI.DLL
0x76140000 - 0x76276000  C:\Windows\System32\MSCTF.dll
0x76280000 - 0x762B6000  C:\Windows\System32\cfgmgr32.dll
0x76320000 - 0x76327000  C:\Windows\System32\NSI.dll
0x76330000 - 0x7638A000  C:\Windows\System32\bcryptPrimitives.dll
0x76390000 - 0x768FE000  C:\Windows\System32\windows.storage.dll
0x76910000 - 0x769D1000  C:\Windows\System32\RPCRT4.dll
0x76AA0000 - 0x76AE1000  C:\Windows\System32\sechost.dll
0x76AF0000 - 0x76B74000  C:\Windows\System32\clbcatq.dll
0x76B80000 - 0x76C60000  C:\Windows\System32\ucrtbase.dll
0x76C60000 - 0x76CF4000  C:\Windows\System32\OLEAUT32.dll
0x76D00000 - 0x76D88000  C:\Windows\System32\shcore.dll
0x76D90000 - 0x76DF3000  C:\Windows\System32\WS2_32.dll
0x76EA0000 - 0x76F80000  C:\Windows\System32\KERNEL32.DLL
0x76F80000 - 0x77121000  C:\Windows\System32\KERNELBASE.dll
0x77130000 - 0x7728F000  C:\Windows\System32\USER32.dll
0x77290000 - 0x772B5000  C:\Windows\System32\IMM32.dll
0x772C0000 - 0x773A5000  C:\Windows\System32\COMDLG32.dll
0x773D0000 - 0x7744B000  C:\Windows\System32\msvcp_win.dll
0x774B0000 - 0x774C5000  C:\Windows\System32\win32u.dll
0x774D0000 - 0x77652000  C:\Windows\SYSTEM32\ntdll.dll

---

```
Memory Dump
```

---

Code: 16 bytes starting at (EIP = 007A2452)

007A2452: 8B 43 04 85  C0 75 09 6A  00 8B CB E8  6E F7 F5 FF  .C...u.j....n...

Stack: 1024 bytes starting at (ESP = 0019FB18)
- = addr                            *\*                                \*  
  0019FB10: 88 21 22 0E  4F 24 7A 00  40 23 7A 00  88 21 22 0E  .!".O$z.@#z..!".
  0019FB20: D8 01 28 26  E4 3F EF 10  40 FB 19 00  AA 61 6F 00  ..(&.?..@....ao.
  0019FB30: 88 21 22 0E  19 00 01 04  FF FF FF FF  D0 01 00 00  .!".............
  0019FB40: 88 FB 19 00  31 92 6F 00  68 00 28 26  88 21 22 0E  ....1.o.h.(&.!".
  0019FB50: 08 08 C7 2A  88 21 22 0E  08 00 01 2F  50 42 6F 00  ..._.!"..../PBo.
  0019FB60: 50 42 6F 00  50 42 6F 00  04 00 00 00  00 00 00 00  PBo.PBo.........
  0019FB70: 40 00 00 00  08 DD AB 2A  08 9C C7 2A  98 01 28 26  @......_..._..(&
  0019FB80: 68 98 C7 2A  88 21 22 0E  98 FB 19 00  EF 65 6F 00  h.._.!"......eo.
  0019FB90: 88 21 22 0E  50 42 6F 00  00 FC 19 00  5B 42 6F 00  .!".PBo.....[Bo.
  0019FBA0: 00 00 00 00  F7 5D 6F 00  00 00 00 00  88 21 22 0E  .....]o......!".
  0019FBB0: 00 00 00 00  00 FC 19 00  08 08 C7 2A  00 00 00 00  ..........._....
  0019FBC0: 88 21 22 0E  9C FB 19 00  DC 5D 6F 00  70 FF 19 00  .!"......]o.p...
  0019FBD0: 00 00 00 00  30 32 43 56  00 00 00 00  30 32 43 56  ....02CV....02CV
  0019FBE0: 00 00 00 00  00 00 00 00  F8 FB 19 00  B8 27 5C 00  .............'.
  0019FBF0: 00 00 00 00  00 00 00 00  50 42 6F 00  88 21 22 0E  ........PBo..!".
  0019FC00: 28 FC 19 00  9B 69 6F 00  44 FC 19 00  08 00 28 26  (....io.D.....(&
  0019FC10: 50 00 00 00  08 08 C7 2A  00 00 00 00  00 00 00 00  P......_........
  0019FC20: 88 21 00 00  44 FC 19 01  4C FC 19 00  3C 42 6F 00  .!..D...L...<Bo.
  0019FC30: 44 FC 19 00  60 00 00 00  50 00 00 00  FF FF FF FF  D...`...P.......
  0019FC40: 88 21 22 0E  68 00 28 26  00 00 00 00  DC FC 19 00  .!".h.(&........
  0019FC50: 9E 51 70 00  00 00 00 00  FE FF FF FF  44 42 47 3A  .Qp.........DBG:
  0019FC60: 4D 42 42 5F  4D 69 6E 69  6D 61 70 42  75 74 74 6F  MBB_MinimapButto
  0019FC70: 6E 46 72 61  6D 65 00 00  08 BA C9 16  00 00 00 00  nFrame..........
  0019FC80: 0E 00 00 00  FF FF FF FF  00 10 D3 27  74 FC 19 00  ...........'t...
  0019FC90: 05 00 00 00  BC FC 19 00  51 70 78 00  AC FC 19 00  ........Qpx.....
  0019FCA0: 08 68 CD 25  F0 FC 19 00  48 F8 D3 25  00 00 00 00  .h.%....H..%....
  0019FCB0: 00 00 00 00  00 00 00 00  00 00 00 00  E0 FC 19 00  ................
  0019FCC0: 00 00 A0 0F  EF DA 2E 00  00 00 00 00  00 00 00 00  ................
  0019FCD0: EA 08 00 00  0C 36 45 11  01 00 00 00  F8 FC 19 00  .....6E.........
  0019FCE0: 47 27 70 00  11 9B 01 00  08 08 C7 2A  48 63 C7 2A  G'p........*Hc.*
  0019FCF0: 84 FC 19 00  28 F8 44 11  10 FD 19 00  08 27 70 00  ....(.D......'p.
  0019FD00: 08 08 C7 2A  30 09 C7 2A  60 51 83 00  24 FD 19 00  ...*0..*`Q..$...
  0019FD10: 2C FD 19 00  E8 B2 76 00  08 08 C7 2A  30 09 C7 2A  ,.....v...._0.._
  0019FD20: 60 51 83 00  00 00 00 40  89 41 02 40  5C FD 19 00  `Q.....@.A.@...
  0019FD30: 13 57 76 00  4A 0C 12 40  88 12 14 05  08 40 EF 10  .Wv.J..@.....@..
  0019FD40: 08 EE 43 11  00 00 00 00  08 40 EF 10  07 00 00 00  ..C......@......
  0019FD50: E4 4C EF 10  0E 00 00 00  28 F8 44 11  6C FD 19 00  .L......(.D.l...
  0019FD60: 45 43 76 00  4A 0C 12 40  20 EE 43 11  34 FE 19 00  ECv.J..@ .C.4...
  0019FD70: 4E 26 44 00  20 EE 43 11  4A 0C 12 40  48 FE 19 00  N&D. .C.J..@H...
  0019FD80: A8 E1 10 05  A8 E1 10 05  00 00 80 3F  00 00 00 00  ...........?....
  0019FD90: 00 00 80 3F  00 00 00 80  38 FE 19 00  C8 CA 1D 0E  ...?....8.......
  0019FDA0: C8 CA 1D 0E  FC FD 19 00  A0 24 B6 02  D8 C7 1D 0E  .........$......
  0019FDB0: E0 DC B5 02  D8 C7 1D 0E  40 00 00 00  00 00 00 00  ........@.......
  0019FDC0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
  0019FDD0: 00 00 00 00  00 00 00 00  00 00 00 00  00 00 80 3F  ...............?
  0019FDE0: 00 00 00 00  00 00 80 3F  00 00 00 80  00 00 80 3F  .......?.......?
  0019FDF0: 00 00 80 40  00 00 80 3F  38 FE 19 00  20 FE 19 00  ...@...?8... ...
  0019FE00: 20 FE 19 00  4F 4B 7A 00  00 00 00 00  00 00 00 00   ...OKz.........
  0019FE10: 00 00 80 3F  00 00 80 3F  00 00 80 3F  00 00 00 00  ...?...?...?....
  0019FE20: 00 00 80 3F  00 00 00 00  00 00 80 3F  00 00 00 00  ...?.......?....
  0019FE30: F5 6A 3A 0F  68 FE 19 00  B0 46 42 00  18 E4 10 05  .j:.h....FB.....
  0019FE40: 08 E4 10 05  00 00 00 00  A8 E1 10 05  35 E5 10 05  ............5...
  0019FE50: 05 00 00 00  A0 E4 10 05  18 E4 10 05  01 00 00 00  ................
  0019FE60: 11 00 00 00  30 E5 10 05  D8 FE 19 00  6F 10 42 00  ....0.......o.B.
  0019FE70: 00 00 00 00  02 01 00 00  08 E4 10 05  00 00 00 00  ................
  0019FE80: 6F 0D 42 00  00 10 40 00  00 00 00 00  00 A0 35 00  o.B...@.......5.
  0019FE90: 45 6E 67 69  6E 65 20 38  32 38 00 00  00 00 00 00  Engine 828......
  0019FEA0: 03 00 00 00  02 00 00 00  65 6E 00 00  00 DB FF 00  ........en......
  0019FEB0: C0 FE 19 00  A2 4E 51 77  47 42 00 00  00 00 00 00  .....NQwGB......
  0019FEC0: 00 A0 35 00  CC DC 53 77  A0 3A 05 77  74 22 00 00  ..5...Sw.:.wt"..
  0019FED0: 05 D2 2E 00  00 00 00 00  F0 FE 19 00  F1 0B 42 00  ..............B.
  0019FEE0: 00 00 00 00  E9 21 40 00  01 00 00 00  01 00 00 00  .....!@.........
  0019FEF0: 80 FF 19 00  1E 41 40 00  A0 99 40 00  00 00 40 00  .....A@...@...@.
  0019FF00: 00 00 00 00  18 24 FD 00  01 00 00 00  00 10 40 00  .....$........@.
  0019FF10: 00 10 40 00  00 A0 35 00  05 00 00 C0  18 24 FD 00  ..@...5......$..

---

# 

Hardware/Driver Information:
Processor:              0x0
Page Size:              4096
Min App Address:        0x10000
Max App Address:        0x7ffeffff
Processor Mask:         0xff
Number of Processors:   8
Processor Type:         586
Allocation Granularity: 65536
Processor Level:        6
Processor Revision:     15363

Percent memory used:    35
Total physical memory:  2147483647
Free Memory:            2147483647
Page file:              -1
Total virtual memory:   2147352576

**Comment by laytya** [comment]
never had crits, try to clean wdb folder.

about scale - there is many addons, and all of them use different way to control minimap icons. So i tryed to catch some, but not all. If all have time ill fix. Fill free to make you own patch to commit...

**Comment by laytya** [comment]
I fixed WIM icon, =) but u need to use this WIM version https://github.com/shirsig/WIM
