### ISSUE TITLE
Choosing between MBB and MBF

### ISSUE THREAD

**Issue by hammerface** [laytya/MinimapButtonBag-vanilla#10]
Hi there, I would have messaged you directly if possible. You seem to have these two addons that fulfill the same function, whats your motivation for working on both, and which would you advocate using between the two? For context, I am using FuBar. Thanks for your time.

**Comment by laytya** [comment]
I personally using MBF, I ported it from TBC and I prefer it. MBB is at very low priority and not updated much.  Somebody like it.
