### ISSUE TITLE
Minimap Buttons don't collapse themself, have to reload ui

### ISSUE THREAD

**Issue by Magoo76** [laytya/MinimapButtonBag-vanilla#11]
Minimap Buttons don't collapse themself, have to reload ui to make them collapse. Pretty annoying. Otherwise this addon is great thanks ! :)

**Comment by Magoo76** [comment]
Nvm I just downloaded MBF your other similar addon and It does the job perfectly :)

**Comment by FrostShock** [comment]
I want to confirm, once I changed the value of the "Collapse Timeout" field, it doesn't collapse anymore
