### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by waytoomuchgaming** [laytya/MinimapButtonBag-vanilla#3]
http://i.imgur.com/a53uEdPl.png%5B/img%5D

**Comment by laytya** [comment]
logout and delete MBB.lua in WTF folder

**Comment by waytoomuchgaming** [comment]
I did.
Same error (and the addon does nothing - but the button is present, and i can access the configuration panel).

**Comment by laytya** [comment]
test new release

**Comment by waytoomuchgaming** [comment]
No more lua error.
But the addon do nothing. Buttons are not attached to it, i tried ctrl right click severall of them, and all other keys combinations that come to my mind, just in case.

**Comment by Thunderhawk2001** [comment]
Similar error, but on line 522. If I click on "Okay", nothing happens. After /reloadui:  line 187 and 552
 Deleted mbb.lua, reinstalled MBB completely. Nothing helped.

**Comment by laytya** [comment]
test it please

**Comment by Thunderhawk2001** [comment]
No more error messages, but after opening the icons, it doesn't close anymore. The options don't work.

**Comment by waytoomuchgaming** [comment]
No change. The addon does nothing, but i can see the button.

**Comment by laytya** [comment]
heh, i cant find any errors now, can u post some addon listing of your interface.

**Comment by waytoomuchgaming** [comment]
AutoBar
aux-addon
aux_merchant_prices
Bagnon
Bagnon_Core
Bagnon_Forever
Bagnon_Options
Banknon
Blizzard_AuctionUI
Blizzard_BattlefieldMinimap
Blizzard_BindingUI
Blizzard_CombatText
Blizzard_CraftUI
Blizzard_GMSurveyUI
Blizzard_InspectUI
Blizzard_MacroUI
Blizzard_RaidUI
Blizzard_TalentUI
Blizzard_TradeSkillUI
Blizzard_TrainerUI
ChatSanitizer
ChatSuey
ChatSuey-ArrowKeys
ChatSuey-ChannelLinks
ChatSuey-EditOnTop
ChatSuey-FontSettings
ChatSuey-ItemLinkHover
ChatSuey-MarkdownLinks
ChatSuey-Mentions
ChatSuey-MiniChannels
ChatSuey-MouseWheel
ChatSuey-PlayerLinks
ChatSuey-RemoveButtons
ChatSuey-StickyChat
ChatSuey-Timestamps
ChatSuey-WebLinks
ClassicSnowFall
Clean_Up_GUI
cooldowns
crafty
CustomNameplates
DebuffTimers
Decursive
DoctorDruid
EquipCompare
FuBar
FuBar_AmmoFu
FuBar_BagFu
FuBar_ClockFu
FuBar_DuraTek
FuBar_GuildFu
FuBar_LocationFu
FuBar_MoneyFu
FuBar_NinjutFu
FuBar_PerformanceFu
FuBar_ToFu
GrimoireKeeper
LazyPig
linkmend
LunaUnitFrames
MetaMap
MetaMapBKP
MetaMapBLT
MetaMapBWP
MetaMapCVT
MetaMapEXP
MetaMapFWM
MetaMapHLP
MetaMapNBK
MetaMapQST
MetaMapWKB
MetaMapZSM
!OmniCC
Postal
!Questie
rais_AutoShot
simpleMinimap
!toggle

**Comment by Thunderhawk2001** [comment]
!ImprovedErrorFrame
!OmniCC
!Questie
AddOns.7z
Atlas
AtlasLoot
AtlasQuest
Bartender2
BetterAlign
BigWigs
Blizzard_AuctionUI
Blizzard_BattlefieldMinimap
Blizzard_BindingUI
Blizzard_CombatText
Blizzard_CraftUI
Blizzard_GMSurveyUI
Blizzard_InspectUI
Blizzard_MacroUI
Blizzard_RaidUI
Blizzard_TalentUI
Blizzard_TradeSkillUI
Blizzard_TrainerUI
Cartographer
Cartographer_Herbalism
Cartographer_Mining
ClassicSnowFall
DPSMate
EQL3
FuBar
FuBar_BagFu
FuBar_Bartender2Fu
FuBar_ClockFu
FuBar_DuraTek
FuBar_ExperienceFu
FuBar_Experienced
FuBar_FuXPFu
FuBar_LocationFu
FuBar_MoneyFu
FuBar_PerformanceFu
KLHThreatMeter
LazyPig
LunaUnitFrames
MBB
MikScrollingBattleText
MikScrollingBattleTextOptions
OneBag
OneBank
OneRing
OneStorage
OneView
Postal
Prat
Prat_FuBar2
Punschrulle
QuickBind
ShaguPlates
SmallerRollFrames
TinyTip
TinyTipExtras
TinyTipOptions
TotemTimers
VCB
WindowsOrdnerListe.txt
XLoot
crafty
cyCircled
linkmend
simpleMinimap
vQueue

**Comment by laytya** [comment]
post screen w/ all buttons around minimap

Close the game. Reinstall addon (remove it first) -  i made folder in archive - just copy it to addons folder. Delete MBB.Lua from WTF folder. Start the game.
and start the game

**Comment by DeTosc** [comment]
> after opening the icons, it doesn't close anymore

I had the same problem. After updating MBB to 504 and DPSmate to B90, everything is working fine now.

**Comment by Thunderhawk2001** [comment]
> I had the same problem. After updating MBB to 504 and DPSmate to B90, everything is working fine 
now.

I've got MBB 504 and DPSmate B90 installed :)

hmm.. ok. After reinstalling several times, enabling/disabling some minimap buttons it now seems to work, altough the settings and Icons are exactly the same . :)

**Comment by DeTosc** [comment]
And now it is getting weird: 
On my laptop. MBB is working fine, as I wrote this afternoon. 
But on my desktop pc, the problem - after opening the icons, it doesn't close anymore - persists :( 
I synchronise my "AddOns"  and my "Account" folder via Dropbox, so I have exactly the same addons and settings on both computers.
???

**Comment by laytya** [comment]
make screens of your buttons

**Comment by waytoomuchgaming** [comment]
Last version, WTF deleted.
Still does nothing.

**Comment by DeTosc** [comment]
![laptop](https://cloud.githubusercontent.com/assets/23533666/22527440/89ea2caa-e8cf-11e6-8cc3-aa63e23847ae.jpg)

Laptop.jpg is the screen of my buttons on my laptop: 
WiM, VQueue, SuperMacro, ShaguDB, Gatherer, DPSMate, Accountant
and MBB 505 is working fine

![desktop](https://cloud.githubusercontent.com/assets/23533666/22527441/89ebd050-e8cf-11e6-9c21-cf7f6956fcd0.jpg)

Desktop.jpg is the screen of my buttons on my Desktop PC:
DPSMate, WiM, VQueue, SuperMacro, ShaguDB, Gatherer, Accountant
and MBB 505 is not closing the buttons. 

I have deleted the MBB.lua file in the WTF folder, still not working

**Comment by laytya** [comment]
DeTosc, make screen of options frame.

Bifidus, make screens of minimap buttons and options frame

**Comment by DeTosc** [comment]
![options](https://cloud.githubusercontent.com/assets/23533666/22543111/6020b050-e92f-11e6-86c8-1f48f6f6d9d4.jpg)

Collaps Timeout is 1 sec (default)

**Comment by waytoomuchgaming** [comment]
http://imgur.com/a/XCnuZ

**Comment by DeTosc** [comment]
I've tried with 0.505a, the buttons are still not closing on my desktop PC.

Isn't it a little bit strange that MBB is ordering the Buttons on my laptop and on my desktop differently?

**Comment by laytya** [comment]
DeTosc, Do u have atlas installed?  and what button is first from MBB button? like 3 coins

**Comment by DeTosc** [comment]
The "3 coins"  button is Accountant. 

I have Atlas installed as part of the Risen UI but I rarely use it, that's why I didn't miss the button... ???  Will check the configuration of Atlas as soon as I am back home.

**Comment by DeTosc** [comment]
Bingo! I've activated the minimap button of Atlas and now it works on my desktop pc as well, version 506

**Comment by laytya** [comment]
fixed in v0.507
