### ISSUE TITLE
Does not catch button from DPSmate (v91)

### ISSUE THREAD

**Issue by Thunderhawk2001** [laytya/MinimapButtonBag-vanilla#4]
MBB does not catch the button from DPSmate.

Open MBB, mouse hovered above DPSmate button, "/mbb buttons" in chat
![wowscrnshot_020217_212650](https://cloud.githubusercontent.com/assets/14139482/22567028/8fa6102c-e98e-11e6-83cd-eff3147631b1.jpg)
(v91).

**Comment by laytya** [comment]
may be it in your ignore list - what if if you Ctrl-Right click on DPS icon?

**Comment by laytya** [comment]
I cant find v91 of DPS Mate =)

point it to me.

v90 works fine.

**Comment by DeTosc** [comment]
Please check the configuration of DPSMate. You have to tick "show minimap button"  on. 

If DPSMate is configured to show its minimap button, MBB will catch it properly.

If DPSMate is configured to not show its minimap button, the button will appear "somewhere" around the minimap.

BTW: the minimap button of SuperMacro behaves likewise: Switch it ON and MBB will catch it properly. Switch it OFF and it will appear "somewhere".

**Comment by laytya** [comment]
I understand - wil see what can i do in next release

**Comment by Thunderhawk2001** [comment]
I've downloaded the v91 from here: https://github.com/Geigerkind/DPSMate

Top right, download zip, extracted the DPSMate folder and copied it to the addon folder. 


Minimap Icon is enabled in DPSmate and if I CTRL + right-click on the DPSmate icon, it opens his right-click dropdown menu, to change some settings.

**Comment by Thunderhawk2001** [comment]
Ok... just tried DPSmate v90, and it's working. :)
