### ISSUE TITLE
[Enhancement] Ability to lock the MBB icon to where its placed in your UI

### ISSUE THREAD

**Issue by sWxJaPkT** [laytya/MinimapButtonBag-vanilla#5]
I find it frustrating when I log into my character and find that the MBB icon has moved slightly and I need to adjust it back to where it is supposed to be.

I have found in the MBB.lua the following code except it does not seem to change where the icon is.

`MBB_DefaultOptions = {
	["ButtonPos"] = {-18, -100},
	["AttachToMinimap"] = 1,
	["CollapseTimeout"] = 1,
	["ExpandDirection"] = 1,
	["MaxButtonsPerLine"] = 0,
	["AltExpandDirection"] = 4,
	["Scale"] = 100,
	["Version"] = MBB_Version`

Here is a screencapture of when I log in https://i.imgur.com/gADTF47.png

Where id like the icon https://i.imgur.com/Updk9sF.png

It doesnt seem to move the same way each time I log in.

Any help is appreciated

**Comment by laytya** [comment]
hm ill see what is happening.

**Comment by laytya** [comment]
test new release

**Comment by sWxJaPkT** [comment]
Works flawlessly! thanks
