### ISSUE TITLE
Lua-error by German-Client

### ISSUE THREAD

**Issue by Mixuspidelix** [laytya/MinimapButtonBag-vanilla#9]
hiho, i have a LuaError with the GermanClient.

Interface\Addons\MBB\MBB.lua:395: attempt to index local ` child' (a nil value)

Thanks Mixus

**Comment by laytya** [comment]
test it plx

**Comment by Mixuspidelix** [comment]
Ok. At the moment, no error. But i cant´t move my Buttons free. They are bind on the Minimap :/ so i can move the Buttons only around the Minimap.
How can i chance this?

Thanks Mixus

edit: ok, when i logged out for 10-15mins. Mbb is resetting and don´t save the settings . than i must relog the game.

**Comment by laytya** [comment]
Just use Minimap Button Frame - its more advanced, i m personaly prefer it.

**Comment by Mixuspidelix** [comment]
Hey Laytya, thanks for the Info but i´m went back now to the MBBv0.312 version. it´s works for me :)

Thanks - Mixus

**Comment by laytya** [comment]
to move out minimap you first need to shift-rightclick it
